---
title: "Ranking de variables usando Teoría de la Información."
output: html_document
---

```{r setup, include=TRUE}
#knitr::opts_chunk$set(echo = TRUE)
#DT::datatable()
```

```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}
library(knitr)
library(funModeling)


```



```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}
sitio_mim <- read.csv("data/tlacotepec_mim.csv")

sitio_mim[is.na(sitio_mim)] <- 0

#maxVal <- max(sitio_mim)

#sitio_normal <- sitio_mim/maxVal

```


```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}


eti_sitio = c(
  'SAAM', 
  'OD_mg.L', 
  'COLI_TOT', 
  'pH_CAMPO', 
  'TEMP_AGUA', 
  'NI_TOT',
  'E_COLI', 
  'HG_TOT', 
  'CR_TOT', 
  'AS_TOT', 
  'TURBIEDAD', 
  'SST', 
  'COLOR_VER',
  'DUR_TOT', 
  'N_TOT', 
  'COLI_FEC', 
  'N_NH3', 
  'N_NO2', 
  'N_NO3')


names_eti_sitio = c(
  'Sustancias Activas al Azul de Metileno',
 'Oxígeno Disuelto',
 'Coliformes Totales',
 'Potencial de Hidrógeno',
 'Temperatura agua',
 'Níquel Total',
 'Escherichia coli',
 'Mercurio Total',
 'Cromo Total',
 'Arsénico Total',
 'Turbiedad',
 'Sólidos Suspendidos Totales',
 'Color Verdadero',
 'Dureza Total',
 'Nitrógeno Total (Cálculo)',
 'Coliformes Fecales',
 'Nitrógeno Amoniacal',
 'Nitrógeno de Nitritos',
 'Nitrógeno de Nitratos')
```
## Gráficas Información Mutua
```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=TRUE, results='asis'}


library(DT)
library(rmarkdown)
knitr::opts_chunk$set(echo = TRUE)



for (i in seq_along(eti_sitio)) {

#Five best variables
  variable_importance = var_rank_info(sitio_mim, eti_sitio[i])
  #var_i <- variable_importance$var
  #mi_i <- variable_importance$mi
  
  #dataframe_i <- data.frame(var_i,mi_i)
  
  #five_rank <- head(dataframe_i[order(-mi_i),],5)
  
  dataframe_i <- data.frame(variable_importance)
  
  five_rank <- head(dataframe_i[order(-dataframe_i$mi),],5)
  
  
  
  
  
  
  #print(names_eti_sitio[i])
  
  #datatable(five_rank)

  #kable()
  #paged_table(five_rank, options = list(rows.print = 15))
  
  #datatable(five_rank, rownames = FALSE, filter="top", options = list(pageLength = 5, scrollX=T))
  cat(paste("\n\n#### test: ", i , "##\n"))
  print(htmltools::tagList(datatable(five_rank)))
  
  #datatable(five_rank)
  #htmltools::tagList(datatable(five_rank))
  
#    print(plot <- ggplot(five_rank, aes(x = reorder(five_rank$var, five_rank$mi),y = five_rank$mi, fill = five_rank$var))
#          + geom_bar(stat = "identity") 
#          + coord_flip() 
#          + theme_bw() 
#          + xlab("") 
#          + ylab("Información Mutua")
#          + ggtitle(names_eti_sitio[i])
#          + theme(plot.title = element_text(hjust = 0.5))
#          + guides(fill = FALSE))
  
  #print
  #print(var_rank_info(sitio_mim, eti_sitio[i]))
  
  #save table in csv
  #name_table <- names_eti_sitio[i]
  #new_name_table <- paste("csv-graphs/tlaco/mi/",name_table,"_mi.csv",sep = "")
 # write.table(var_rank_info(sitio_mim, eti_sitio[i]), file = new_name_table, sep = ",", col.names = NA)
  

  
  
}

datatable(five_rank)


```
