---
title: "Índice Metztitlán 1"
output: html_document
---

Dra. Melanie Kolb

M. en F. C. Gustavo Magallanes-Guijón

Dr. Oliver López-Corona

```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}
library(knitr)
library(funModeling)
library(DT)

```

```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}
sitio_mim <- read.csv("data/metztitlan_1_mim.csv")

```

```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE}

eti_sitio = c(
  'E_COLI', 
  'HG_TOT', 
  'TURBIEDAD', 
  'SST', 
  'COLOR_VER', 
  'DUR_TOT', 
  'N_TOT',
  'COLI_FEC', 
  'N_NH3', 
  'N_NO2', 
  'N_NO3')

names_eti_sitio = c(
  'Escherichia coli',
 'Mercurio Total',
 'Turbiedad',
 'Sólidos Suspendidos Totales',
 'Color Verdadero',
 'Dureza Total',
 'Nitrógeno Total (Cálculo)',
 'Coliformes Fecales',
 'Nitrógeno Amoniacal',
 'Nitrógeno de Nitritos',
 'Nitrógeno de Nitratos')
```
# 5 variables mejor rankeadas tomando todas las variables una la variable objetivo
```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE, results='asis'}

library(DT)
#library(rmarkdown)

#knitr::opts_chunk$set(echo = TRUE)

for (i in seq_along(eti_sitio)) {

#Five best variables
  variable_importance = var_rank_info(sitio_mim, eti_sitio[i])

  dataframe_i <- data.frame(variable_importance)
  
  five_rank <- head(dataframe_i[order(-dataframe_i$mi),],5)

  
#Five best variables reverse
  variable_importance_rev = var_rank_info(sitio_mim, eti_sitio[length(eti_sitio)-i+1])

  dataframe_i_rev <- data.frame(variable_importance_rev)
  
  five_rank_rev <- head(dataframe_i_rev[order(-dataframe_i_rev$mi),],5)  
  
  
  #paged_table(five_rank, options = list(rows.print = 15))
  #datatable(five_rank, rownames = FALSE, filter="top", options = list(pageLength = 5, scrollX=T))
  cat(paste("\n\n####", names_eti_sitio[i] , "##\n\n\n\n\n"))
  #print(htmltools::tagList(datatable(variable_importance)))
  print(kable(five_rank))
  
  #print(myplot <- ggplot(var_rank_info(sitio_mim,  eti_sitio[i]), aes(x = reorder(var, mi),y = mi, fill = var))
   #       + geom_bar(stat = "identity") 
    #      + coord_flip() 
     #     + theme_bw() 
      #    + xlab("")
       #   + ylab("Información Mutua")
        #  + ggtitle(names_eti_sitio[i])
         # + theme(plot.title = element_text(hjust = 0.5))
          #+ guides(fill = FALSE))
  
  
  interseccion <- intersect(five_rank$var, five_rank_rev$var)
  
#for (j in seq_along(interseccion)) {  
  idx <- five_rank[is.element(five_rank$var, interseccion)]
    #idx = five_rank[grepl(five_rank$var, interseccion[j]),]
  
  
  indice_tlacotepec = sqrt(mean(idx$mi)^2 + mean(idx$ig)^2)
 # }
}

#print(kable(indice_tlacotepec, caption = "Indice: "))
#print(kable(interseccion, caption = "Variables de intersección"))

#datatable(indice_tlacotepec)
#datatable(five_rank)

```
Variables en las que se intersectan:
```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE, results='asis'}

kable(interseccion)

```
Índice obtenido

$$
  Índice = \sqrt{(mi)^2 + (ig)^2}
$$
```{r eval=TRUE, warning=FALSE, message=FALSE, error=FALSE, echo=FALSE, results='asis'}



#kable(indice_tlacotepec, caption = "Indice: ")
print(indice_tlacotepec)


```